# This file is a general .xdc for the Basys3 rev B board
# To use it in a project:
# - uncomment the lines corresponding to used pins
# - rename the used ports (in each line, after get_ports) according to the top level signal names in the project

# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports clk]

# Switches
set_property PACKAGE_PIN V17 [get_ports {msg_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {msg_in[0]}]
set_property PACKAGE_PIN V16 [get_ports {msg_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {msg_in[1]}]
set_property PACKAGE_PIN W16 [get_ports {msg_in[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {msg_in[2]}]
set_property PACKAGE_PIN W17 [get_ports {msg_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {msg_in[3]}]
set_property PACKAGE_PIN W15 [get_ports {msg_in[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {msg_in[4]}]
set_property PACKAGE_PIN V15 [get_ports {msg_in[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {msg_in[5]}]
set_property PACKAGE_PIN W14 [get_ports {msg_in[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {msg_in[6]}]
set_property PACKAGE_PIN W13 [get_ports {msg_in[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {msg_in[7]}]
#set_property PACKAGE_PIN V2 [get_ports {s1}]
# 	set_property IOSTANDARD LVCMOS33 [get_ports {s1}]
#set_property PACKAGE_PIN T3 [get_ports {j}]
# 	set_property IOSTANDARD LVCMOS33 [get_ports {j}]
#set_property PACKAGE_PIN T2 [get_ports {k}]
# 	set_property IOSTANDARD LVCMOS33 [get_ports {k}]
#set_property PACKAGE_PIN R3 [get_ports {sw[11]}]
# 	set_property IOSTANDARD LVCMOS33 [get_ports {sw[11]}]
#set_property PACKAGE_PIN W2 [get_ports {sw[12]}]
# 	set_property IOSTANDARD LVCMOS33 [get_ports {sw[12]}]
##set_property PACKAGE_PIN U1 [get_ports {reset}]
# 	set_property IOSTANDARD LVCMOS33 [get_ports {reset}]
#set_property PACKAGE_PIN T1 [get_ports {sB}]
# 	set_property IOSTANDARD LVCMOS33 [get_ports {sB}]
set_property PACKAGE_PIN R2 [get_ports {a_send}]
 	set_property IOSTANDARD LVCMOS33 [get_ports {a_send}]

# LEDs
set_property PACKAGE_PIN U16 [get_ports {led_txbuf[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_txbuf[0]}]
set_property PACKAGE_PIN E19 [get_ports {led_txbuf[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_txbuf[1]}]
set_property PACKAGE_PIN U19 [get_ports {led_txbuf[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_txbuf[2]}]
set_property PACKAGE_PIN V19 [get_ports {led_txbuf[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_txbuf[3]}]
set_property PACKAGE_PIN W18 [get_ports {led_txbuf[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_txbuf[4]}]
set_property PACKAGE_PIN U15 [get_ports {led_txbuf[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_txbuf[5]}]
set_property PACKAGE_PIN U14 [get_ports {led_txbuf[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_txbuf[6]}]
set_property PACKAGE_PIN V14 [get_ports {led_txbuf[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_txbuf[7]}]
#set_property PACKAGE_PIN V13 [get_ports {led_rxbuf[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_rxbuf[0]}]
#set_property PACKAGE_PIN V3 [get_ports {led_rxbuf[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_rxbuf[1]}]
set_property PACKAGE_PIN W3 [get_ports {current_page_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {current_page_led[1]}]
set_property PACKAGE_PIN U3 [get_ports {current_page_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {current_page_led[0]}]
#set_property PACKAGE_PIN P3 [get_ports {led_rxbuf[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_rxbuf[4]}]
#set_property PACKAGE_PIN N3 [get_ports {led_rxbuf[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_rxbuf[5]}]
#set_property PACKAGE_PIN P1 [get_ports {led_rxbuf[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_rxbuf[6]}]
set_property PACKAGE_PIN L1 [get_ports {current_reg_led}]
set_property IOSTANDARD LVCMOS33 [get_ports {current_reg_led}]


##7 segment display
set_property PACKAGE_PIN W7 [get_ports {dsp_cathodes[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dsp_cathodes[6]}]
set_property PACKAGE_PIN W6 [get_ports {dsp_cathodes[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dsp_cathodes[5]}]
set_property PACKAGE_PIN U8 [get_ports {dsp_cathodes[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dsp_cathodes[4]}]
set_property PACKAGE_PIN V8 [get_ports {dsp_cathodes[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dsp_cathodes[3]}]
set_property PACKAGE_PIN U5 [get_ports {dsp_cathodes[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dsp_cathodes[2]}]
set_property PACKAGE_PIN V5 [get_ports {dsp_cathodes[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dsp_cathodes[1]}]
set_property PACKAGE_PIN U7 [get_ports {dsp_cathodes[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dsp_cathodes[0]}]
set_property PACKAGE_PIN V7 [get_ports dsp_dp]
set_property IOSTANDARD LVCMOS33 [get_ports dsp_dp]
set_property PACKAGE_PIN U2 [get_ports {dsp_anodes[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dsp_anodes[0]}]
set_property PACKAGE_PIN U4 [get_ports {dsp_anodes[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dsp_anodes[1]}]
set_property PACKAGE_PIN V4 [get_ports {dsp_anodes[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dsp_anodes[2]}]
set_property PACKAGE_PIN W4 [get_ports {dsp_anodes[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dsp_anodes[3]}]

##Buttons
set_property PACKAGE_PIN U18 [get_ports send]
set_property IOSTANDARD LVCMOS33 [get_ports send]
set_property PACKAGE_PIN T18 [get_ports switch_reg]
 	set_property IOSTANDARD LVCMOS33 [get_ports switch_reg]
set_property PACKAGE_PIN W19 [get_ports switch_page_left]
 	set_property IOSTANDARD LVCMOS33 [get_ports switch_page_left]
set_property PACKAGE_PIN T17 [get_ports switch_page_right]
 	set_property IOSTANDARD LVCMOS33 [get_ports switch_page_right]
set_property PACKAGE_PIN U17 [get_ports load]
set_property IOSTANDARD LVCMOS33 [get_ports load]

###Pmod Header JA
##Sch name = JA1
set_property PACKAGE_PIN J1 [get_ports TX]
set_property IOSTANDARD LVCMOS33 [get_ports TX]
#Sch name = JA2
set_property PACKAGE_PIN L2 [get_ports RX]
set_property IOSTANDARD LVCMOS33 [get_ports RX]

set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
